token:
  expiration_time: 386400000
  secret: {cipher}AYCOhrwxXTxjcstyG6OlVRTZKQf9l9pLQ2qpklSsB02DMlWI7AZr5WLGcJ5ytPo7nuuUcSMBBR47aS0K3Yiq1fxFd8zQXQ0kfhzCE2a1ey3QF1V1g//PgjZMAqIMTojdww/98KGE2y90BzN3vdmeHHesTWKMJidPn7clhOipJqxy8PjAxWCXBeTrNWKg9n/J3IiTi+H2HvLk1K1woKHbqssc012qKCdma4nZXadgw0HlmFBv82BLTdjuXvt2L8P02M2S/+nvQg7WnZQ+QX+9Dm5RwFxsT0PTp9LM+N9X4Mgt80T9HxRDaX1spqGhFFnUHrWTOSP0GImgh8S6Y2RVX3jxgB54eIhS73NhUN11QZd+3fxFkng9g9HVVeHr2N4hv9fTJm5KORBugpxdYJzfxJvamELXpm0lPM+6uE5GDDYZgkzhxhfISS3rLHERI54+ZKyTCR0vkJrpu7qpG4CCuJRYxkW+1tp9t1jVZZIPedUFY0YVW7jC5IM2vp6H0RNJFUZGd9WqNju4GVkEMShbwmUshfNvnPhRyw6gH9TUTDPvBe1ShvdTzU+3slNEUlLCMG5G1aj1U/M6O1z248w3RHqEgd7eBgrwTKylIkZAfRb+FF7/9Bsz8Z4Dc0hnoGOqUPI=

  
gateway:
  ip: 172.18.0.5

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AYBznKKB4pTMIF2Gkr+jD2N8kn4vMtxuKVYPn2JcI3vf3f/7MxamHpiqjn+UgRzJRmWu6lNmPr16IyuVG2PognI3guPwKrzTJMViBlsUMEeSsrpzEDBrRhWCBAL88vEv/20uo49Li1MmyGH2qqkW3Vn3qR9RHVpwPUZNzch4SHRVGsxcpf9OsXAOIThv0wMmkEiM5vRWNlhA23kTksO+nKKhhBKruG1FQ1ZDTTV0REBBjxNAvduQKkip1OjCqrHFc/mWtOFofgWhxuRLY75D+Hs8U+ytIaH8+8KYeNlV0DRZg1/4V49tvgeREgmM1ocxxdywr3FKb4HXTAvhGAMgCWsKiv4gWEl5/i5lQHSQomSP27JaUM7FHTMLpD0P9Bqd+Z11GG0eg14SRFK6dJsFGhzHI9BTFUtlQaUsMs4dFK3UCWgkXy7//UtrUPlaEWpI9w55+eC7qwCd6pSa48MnZYtakbrLxGsz/+G3y+HlB5zoGwyB83/bP63tbkRM8FJWb0bB7/L2u+iE9OzTdXFXMka2o4FzZ59CLLl8fgxKkpYAeQ=='

order_service:
  url: http://order-service/order-service/%s/orders
  exception:
    order_is_empty: User's orders is empty
